### PR TITLE
Initialize Go Module

### PR DESCRIPTION
**Pull request by probably-not**
As of Go1.13, go modules are standardized and the default mode.

This initializes a go module through `go mod init` and updates references to the old bloom repo's url (https://github.com/willf/bloom) to the new repo, found [here](https://github.com/bits-and-blooms/bloom).

Another interesting bit of information:
After updating the reference to the new bloom filter's repo, I ran the benchmarks to check performance. When running the benchmarks on my machine, it looks like the latest versions of the bloom filter are much faster than the original. This library is still much faster, but not by as much.

Benchmark Results:
```
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkBloomFilter-16                                  7416015               159.9 ns/op
BenchmarkMapLookup-16                                   59552816                17.89 ns/op
BenchmarkUnpackedFilterLookup-16                        41260158                30.24 ns/op
BenchmarkUnpackedDiskFilterLookup-16                      843660              1589 ns/op
BenchmarkPackedDiskFilterLookup-16                       1000000              1342 ns/op
BenchmarkUnpackedFilterLookupWithFNV-16                 23550657                49.83 ns/op
BenchmarkPackedFilterLookup-16                          27943140                43.31 ns/op
BenchmarkUnpackedSerialize-16                              14469            104828 ns/op
BenchmarkUnpackedDeserialize-16                             3274            310236 ns/op
BenchmarkUnpackedExternalOpen-16                           69052             16958 ns/op
BenchmarkPackedSerialize-16                                17650             77425 ns/op
BenchmarkPackedDeserialize-16                               4242            252947 ns/op
BenchmarkPackedFilterLookupWithFNV-16                   10316174               112.1 ns/op
BenchmarkUnpackedFilterLookupWithExternalStorage-16     36980121                32.42 ns/op
BenchmarkLoading-16                                     10425559               181.1 ns/op
```

### CODE REVIEW

**Comment by probably-not** [comment]
@lloyd @tmm1 @fannheyward
Can someone take a look at this? It would be very helpful in solving compatibility problems with modern Go releases.

**Comment by lloyd** [comment]
awesome, verified and reviewed and it looks great.  Thanks for modernizing!

**Comment by lloyd** [comment]
Also, I'll re-run benchmarks and update the README!  Thanks for the heads up on the improved performance of the referenced bloom filter implementation, @probably-not! 🙏🏻

**Comment by probably-not** [comment]
Thanks @lloyd! Happy this got merged in, we started using this module a few months ago and it made a massive impact, happy to help make sure it's updated and modernized.

Re: Benchmarks, one added suggestion would be to add in the machine details that Go's Benchmarking functionality prints out at the top of the output. It helps explain what the results mean, since benchmarks are affected by the underlying hardware.

**Pull request merged**
